Downgrade because bug in middleman-deploy version 0.2.1
RSync deploy bug: /lib/middleman-deploy/methods/rsync.rb:32:in
`process': undefined method `run' for
#<Middleman::Deploy::Methods::Rsync:0x007f85aed8a190> (NoMethodError)